<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title ?? 'API Documentation' }}</title>
    <style>
        body {
            margin: 0;
            font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", sans-serif;
            background: #f7f8fa;
        }
        .spectrum-header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: #fff;
            padding: 20px 40px;
        }
        .spectrum-header h1 {
            margin: 0;
            font-size: 24px;
        }
        .spectrum-header .version {
            margin-left: 10px;
            font-size: 12px;
            background: rgba(255, 255, 255, 0.2);
            border-radius: 999px;
            padding: 2px 10px;
        }
        .spectrum-header p {
            margin: 8px 0 0;
            opacity: 0.9;
            font-size: 14px;
        }
        .spectrum-footer {
            text-align: center;
            padding: 16px;
            color: #666;
            font-size: 12px;
        }
    </style>
</head>
<body>
    <div class="spectrum-header">
        <h1>
            {{ $title ?? 'API Documentation' }}
            <span class="version">v{{ $version ?? '1.0.0' }}</span>
        </h1>
        @if(!empty($description))
        <p>{{ $description }}</p>
        @endif
    </div>

    <rapi-doc
        id="rapidoc"
        theme="{{ $rapidocTheme ?? 'light' }}"
        render-style="{{ $rapidocRenderStyle ?? 'read' }}"
        schema-style="{{ $rapidocSchemaStyle ?? 'tree' }}"
        show-header="false"
    ></rapi-doc>

    <div class="spectrum-footer">
        Generated by <a href="https://github.com/wadakatu/laravel-spectrum" target="_blank">Laravel Spectrum</a>
        on {{ $generatedAt ?? date('Y-m-d H:i:s') }}
    </div>

    <script type="module" src="https://unpkg.com/rapidoc/dist/rapidoc-min.js"></script>
    <script>
        const spec = {!! $spec !!};
        document.getElementById('rapidoc').spec = spec;
    </script>
</body>
</html>
