<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{{ $title ?? 'API Documentation' }}</title>
    <link rel="stylesheet" type="text/css" href="https://unpkg.com/swagger-ui-dist@5/swagger-ui.css">
    <style>
        html {
            box-sizing: border-box;
            overflow-y: scroll;
        }
        *,
        *:before,
        *:after {
            box-sizing: inherit;
        }
        body {
            margin: 0;
            background: #fafafa;
        }
        .swagger-ui .topbar {
            display: none;
        }
        .spectrum-header {
            background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
            color: white;
            padding: 20px 40px;
            box-shadow: 0 2px 10px rgba(0,0,0,0.1);
        }
        .spectrum-header h1 {
            margin: 0 0 5px 0;
            font-size: 24px;
            font-weight: 600;
        }
        .spectrum-header p {
            margin: 0;
            opacity: 0.9;
            font-size: 14px;
        }
        .spectrum-header .version {
            display: inline-block;
            background: rgba(255,255,255,0.2);
            padding: 2px 10px;
            border-radius: 12px;
            font-size: 12px;
            margin-left: 10px;
        }
        .spectrum-footer {
            text-align: center;
            padding: 20px;
            color: #666;
            font-size: 12px;
            border-top: 1px solid #eee;
            margin-top: 40px;
        }
        .spectrum-footer a {
            color: #667eea;
            text-decoration: none;
        }
        .spectrum-footer a:hover {
            text-decoration: underline;
        }
    </style>
</head>
<body>
    <div class="spectrum-header">
        <h1>
            {{ $title ?? 'API Documentation' }}
            <span class="version">v{{ $version ?? '1.0.0' }}</span>
        </h1>
        @if(!empty($description))
        <p>{{ $description }}</p>
        @endif
    </div>

    <div id="swagger-ui"></div>

    <div class="spectrum-footer">
        Generated by <a href="https://github.com/wadakatu/laravel-spectrum" target="_blank">Laravel Spectrum</a>
        on {{ $generatedAt ?? date('Y-m-d H:i:s') }}
    </div>

    <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-bundle.js"></script>
    <script src="https://unpkg.com/swagger-ui-dist@5/swagger-ui-standalone-preset.js"></script>
    <script>
        window.onload = function() {
            const spec = {!! $spec !!};

            window.ui = SwaggerUIBundle({
                spec: spec,
                dom_id: '#swagger-ui',
                deepLinking: true,
                presets: [
                    SwaggerUIBundle.presets.apis,
                    SwaggerUIStandalonePreset
                ],
                plugins: [
                    SwaggerUIBundle.plugins.DownloadUrl
                ],
                layout: "StandaloneLayout",
                defaultModelsExpandDepth: 1,
                defaultModelExpandDepth: 1,
                docExpansion: "list",
                filter: true,
                showExtensions: true,
                showCommonExtensions: true,
                tryItOutEnabled: {{ $tryItOutEnabled ? 'true' : 'false' }},
                persistAuthorization: true,
                displayRequestDuration: true
            });
        };
    </script>
</body>
</html>
