<?php

return [
    /*
    |--------------------------------------------------------------------------
    | API Documentation Title
    |--------------------------------------------------------------------------
    |
    | The title of your API documentation. This will be displayed at the top
    | of the generated documentation.
    |
    */
    'title' => env('APP_NAME', 'Laravel').' API',

    /*
    |--------------------------------------------------------------------------
    | API Version
    |--------------------------------------------------------------------------
    |
    | The version of your API. This will be included in the OpenAPI spec.
    |
    */
    'version' => '1.0.0',

    /*
    |--------------------------------------------------------------------------
    | API Description
    |--------------------------------------------------------------------------
    |
    | A description of your API that will be included in the documentation.
    |
    */
    'description' => 'API documentation generated by Laravel Prism',

    /*
    |--------------------------------------------------------------------------
    | Route Patterns
    |--------------------------------------------------------------------------
    |
    | The route patterns that should be included in the documentation.
    | Use wildcards to match multiple routes.
    |
    */
    'route_patterns' => [
        'api/*',
        'api/v1/*',
        'api/v2/*',
    ],

    /*
    |--------------------------------------------------------------------------
    | Excluded Routes
    |--------------------------------------------------------------------------
    |
    | Specific routes that should be excluded from the documentation.
    |
    */
    'excluded_routes' => [
        'api/health',
        'api/ping',
    ],

    /*
    |--------------------------------------------------------------------------
    | Authentication Configuration
    |--------------------------------------------------------------------------
    |
    | Configure how authentication is detected and documented.
    |
    */
    'authentication' => [
        /*
        | Global authentication settings
        */
        'global' => [
            'enabled' => false,
            'scheme' => [
                'type' => 'http',
                'scheme' => 'bearer',
                'bearerFormat' => 'JWT',
                'description' => 'Global JWT authentication',
                'name' => 'globalAuth',
            ],
            'required' => false,
        ],

        /*
        | Custom authentication schemes
        | Map middleware names to OpenAPI security schemes
        */
        'custom_schemes' => [
            // 'custom-auth' => [
            //     'type' => 'apiKey',
            //     'in' => 'header',
            //     'name' => 'X-Custom-Token',
            //     'description' => 'Custom API token',
            //     'name' => 'customAuth',
            // ],
        ],

        /*
        | Pattern-based authentication
        | Apply authentication to routes matching patterns
        */
        'patterns' => [
            // 'api/admin/*' => [
            //     'scheme' => [...],
            //     'required' => true,
            // ],
        ],

        /*
        | OAuth2 configuration for Passport
        */
        'oauth2' => [
            'authorization_url' => env('APP_URL').'/oauth/authorize',
            'token_url' => env('APP_URL').'/oauth/token',
            'refresh_url' => env('APP_URL').'/oauth/token',
            'scopes' => [
                // 'read' => 'Read access',
                // 'write' => 'Write access',
            ],
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Cache Configuration
    |--------------------------------------------------------------------------
    |
    | Configure the caching behavior for analysis results.
    |
    */
    'cache' => [
        /*
        |--------------------------------------------------------------------------
        | Enable Cache
        |--------------------------------------------------------------------------
        |
        | When enabled, analysis results will be cached to speed up subsequent
        | documentation generation.
        |
        */
        'enabled' => env('PRISM_CACHE_ENABLED', true),

        /*
        |--------------------------------------------------------------------------
        | Cache Directory
        |--------------------------------------------------------------------------
        |
        | The directory where cache files will be stored.
        |
        */
        'directory' => storage_path('app/spectrum/cache'),

        /*
        |--------------------------------------------------------------------------
        | Cache TTL
        |--------------------------------------------------------------------------
        |
        | Time to live for cache files in seconds. Set to null for no expiration.
        |
        */
        'ttl' => env('PRISM_CACHE_TTL', null),

        /*
        |--------------------------------------------------------------------------
        | Watch Files
        |--------------------------------------------------------------------------
        |
        | Additional files to watch for changes that should invalidate the cache.
        |
        */
        'watch_files' => [
            base_path('composer.json'),
            base_path('composer.lock'),
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Watch Configuration
    |--------------------------------------------------------------------------
    |
    | Configure the file watching behavior for real-time preview.
    |
    */
    'watch' => [
        /*
        |--------------------------------------------------------------------------
        | File Watching
        |--------------------------------------------------------------------------
        |
        | Configure which directories and files to watch for changes.
        |
        */
        'paths' => [
            app_path('Http/Controllers'),
            app_path('Http/Requests'),
            app_path('Http/Resources'),
            base_path('routes'),
        ],

        /*
        |--------------------------------------------------------------------------
        | Watch Ignore Patterns
        |--------------------------------------------------------------------------
        |
        | Files matching these patterns will be ignored.
        |
        */
        'ignore' => [
            '*.log',
            '*.cache',
            '.git',
            'vendor',
            'node_modules',
        ],

        /*
        |--------------------------------------------------------------------------
        | Debounce Time
        |--------------------------------------------------------------------------
        |
        | Wait this many milliseconds after a file change before regenerating.
        | Useful to avoid multiple regenerations when saving multiple files.
        |
        */
        'debounce' => 300,
    ],

    /*
    |--------------------------------------------------------------------------
    | Validation Analysis
    |--------------------------------------------------------------------------
    |
    | Configure how validation rules are detected and analyzed.
    |
    */
    'validation' => [
        /*
        |--------------------------------------------------------------------------
        | Validation Analysis
        |--------------------------------------------------------------------------
        */
        'analyze_inline' => true, // インラインバリデーションを解析
        'analyze_form_requests' => true, // FormRequestを解析

        /*
        |--------------------------------------------------------------------------
        | Lumen Compatibility
        |--------------------------------------------------------------------------
        */
        'lumen' => [
            'enabled' => env('PRISM_LUMEN_MODE', false),
            'default_middleware' => ['api'], // Lumenのデフォルトミドルウェア
        ],
    ],

    /*
    |--------------------------------------------------------------------------
    | Response Transformer Support
    |--------------------------------------------------------------------------
    |
    | Configure support for various response transformation libraries.
    |
    */
    'transformers' => [
        /*
        |--------------------------------------------------------------------------
        | Enabled Transformers
        |--------------------------------------------------------------------------
        |
        | Supported transformers for API response analysis
        |
        */
        'enabled' => [
            'laravel-resource' => true,
            'fractal' => true,
        ],

        /*
        |--------------------------------------------------------------------------
        | Fractal Settings
        |--------------------------------------------------------------------------
        |
        | Configuration specific to Fractal transformer support
        |
        */
        'fractal' => [
            // Default serializer format
            'default_serializer' => 'array', // array, data_array, json_api

            // How to handle includes in OpenAPI
            'include_handling' => 'optional_properties', // optional_properties or separate_endpoints

            // Default pagination schema for collections
            'pagination_schema' => [
                'type' => 'object',
                'properties' => [
                    'data' => ['type' => 'array'],
                    'meta' => [
                        'type' => 'object',
                        'properties' => [
                            'pagination' => [
                                'type' => 'object',
                                'properties' => [
                                    'total' => ['type' => 'integer'],
                                    'count' => ['type' => 'integer'],
                                    'per_page' => ['type' => 'integer'],
                                    'current_page' => ['type' => 'integer'],
                                    'total_pages' => ['type' => 'integer'],
                                ],
                            ],
                        ],
                    ],
                ],
            ],
        ],
    ],
];
