<?php

return [
    /*
    |--------------------------------------------------------------------------
    | API Documentation Title
    |--------------------------------------------------------------------------
    |
    | The title of your API documentation. This will be displayed at the top
    | of the generated documentation.
    |
    */
    'title' => env('APP_NAME', 'Laravel') . ' API',

    /*
    |--------------------------------------------------------------------------
    | API Version
    |--------------------------------------------------------------------------
    |
    | The version of your API. This will be included in the OpenAPI spec.
    |
    */
    'version' => '1.0.0',

    /*
    |--------------------------------------------------------------------------
    | API Description
    |--------------------------------------------------------------------------
    |
    | A description of your API that will be included in the documentation.
    |
    */
    'description' => 'API documentation generated by Laravel Prism',

    /*
    |--------------------------------------------------------------------------
    | Route Patterns
    |--------------------------------------------------------------------------
    |
    | The route patterns that should be included in the documentation.
    | Use wildcards to match multiple routes.
    |
    */
    'route_patterns' => [
        'api/*',
        'api/v1/*',
        'api/v2/*',
    ],

    /*
    |--------------------------------------------------------------------------
    | Excluded Routes
    |--------------------------------------------------------------------------
    |
    | Specific routes that should be excluded from the documentation.
    |
    */
    'excluded_routes' => [
        'api/health',
        'api/ping',
    ],
];